---
- name: install mysql
  yum:
    name: "{{ mysql_url }}/{{ item.rpm }}"
    state: present
  with_items: "{{ mysql_items }}"
  tags: mysql

- name: add mysql to service
  service:
    name: mysql
    state: restarted
    enabled: yes
  tags: mysql

- name: get mysql password
  shell: cat /root/.mysql_secret | awk '{print $18}'
  register: mysql_root_password
  tags: mysql

- name: setup mysql root
  command: mysqladmin -uroot -p{{ mysql_root_password.stdout }} password {{ mysql_root_password.stdout }}
  tags: mysql

- name: copys my.cnf
  template:
    src: .my.cnf.j2
    dest: /root/.my.cnf
    owner: root
    mode: 0600
  tags: mysql

- name: add yum repository
  yum:
    name: "{{ item }}"
    state: present
  with_items:
  - http://ftp-srv2.kddilabs.jp/Linux/distributions/fedora/epel/6/x86_64/epel-release-6-8.noarch.rpm
  - http://rpms.famillecollet.com/enterprise/remi-release-6.rpm

- name: change repository default setting to disabled
  replace:
    dest: /etc/yum.repos.d/{{item}}
    regexp: "enabled *= *1"
    replace: "enabled=0"
  with_items:
  - epel.repo
  - remi.repo

- name: install mysql-python
  yum:
    name: MySQL-python
    enablerepo: epel
    state: installed
  tags: mysql

