---
- name: install mysql
  yum: name={{ mysql_url }}/{{ item.rpm }} state=present
  with_items: mysql_items
  tags: mysql2

- name: add mysql to service
  service: name=mysql state=restarted enabled=yes
  tags: mysql

- name: get mysql password
  shell: cat /root/.mysql_secret | awk '{print $18}'
  register: mysql_root_password
  tags: mysql

- name: setup mysql root
  command: mysqladmin -uroot -p{{ mysql_root_password.stdout }} password {{ mysql_root_password.stdout }}
  tags: mysql

- name: copys my.cnf
  tags: mysql
  template: src=.my.cnf.j2 dest=/root/.my.cnf owner=root mode=0600

- name: install mysql-python
  yum: name=MySQL-python enablerepo=epel state=installed
  tags: mysql

