---
- name: add nginx group
  group: name=nginx

- name: add nginx user
  user: name=nginx group=nginx system=yes shell=/sbin/nologin

- name: install nginx
  yum: name=nginx state=present

- name: copy]nginx conf file
  template: src=default.conf.j2 dest=/etc/nginx/conf.d/default.conf owner=root group=root mode=644
  notify: restart nginx

- name: add nginx to service
  service: name=nginx state=started enabled=yes

