---
- name: install php modules
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - php
    - php-mysql
    - php-mbstring
    - php-fpm
  tags: php

- name: copy php.ini
  template:
    src: php.ini.j2
    dest: /etc/php.ini
    owner: root
    group: root
    mode: 644

- name: add php-fpm to service
  service:
    name: php-fpm
    state: started
    enabled: yes

